name: Code to Manul Python
author: parkhs21

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Test py file
      shell: bash
      run: python main.py
