name: Code to Manul Python
author: parkhs21

inputs:
  openai-key:
    required: true

runs:
  using: "composite"
  steps:
    - name: Set up python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -q -r $GITHUB_ACTION_PATH/requirements.txt
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Test py file
      shell: bash
      run: python $GITHUB_ACTION_PATH/main.py
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}
