name: Code to Manul Python
author: parkhs21

inputs:
  openai-key:
    required: true

runs:
  using: "composite"
  defaults:
    run:
      shell: bash

  steps:
    - name: Set up Path Env
      run: echo "GITHUB_ACTION_PATH=$GITHUB_ACTION_PATH" >> "$GITHUB_ENV"
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Set up python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -q -r $GITHUB_ACTION_PATH/requirements.txt

    - name: Test py file
      run: python $GITHUB_ACTION_PATH/main.py
