name: Code to Manul Python
author: parkhs21

inputs:
  openai-key:
    required: true
outputs:
  result:
    value: ${{ steps.test-python.outputs.result }}

runs:
  using: "composite"
  steps:
    - name: Set Path Env
      shell: bash
      run: echo "GITHUB_ACTION_PATH=$GITHUB_ACTION_PATH" >> "$GITHUB_ENV"
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Set up python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    # - name: Install dependencies
    #   shell: bash
    #   run: |
    #     python -q -m pip install --upgrade pip
    #     pip install -q -r $GITHUB_ACTION_PATH/requirements.txt

    # - name: Set dotenv file
    #   shell: bash
    #   run: echo OPENAI_API_KEY=${{ inputs.openai-key }} > $GITHUB_ACTION_PATH/.env

    # - name: Test py file
    #   shell: bash
    #   id: test-python
    #   run: python $GITHUB_ACTION_PATH/main.py

    # - name: Upload file
    #   uses: actions/upload-artifact@v4
    #   id: upload-step
    #   with:
    #     name: test-file
    #     path: test.adoc

    # - name: Update comment
    #   uses: peter-evans/create-or-update-comment@v2
    #   with:
    #     issue-number: 2
    #     body: |-
    #       ## Test
    #       ${{ steps.upload-step.outputs.artifact-url }}

    - name: create issue
      uses: dacbd/create-issue-action@main
      with:
        title: test issue
        content-filepath: $GITHUB_ACTION_PATH/test.md

