name: Code to Manul Python
author: parkhs21

inputs:
  openai-token:
    required: true

runs:
  using: "composite"
  steps:
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r $GITHUB_ACTION_PATH/requirements.txt
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Test py file
      shell: bash
      run: python $GITHUB_ACTION_PATH/main.py
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: temp
      shell: bash
      run: echo "$OPENAI_TOKEN"
      env:
        OPENAI_TOKEN: ${{ inputs.openai-token }}
