name: Code to Manul Python
author: parkhs21

inputs:
  openai-key:
    required: true

runs:
  using: "composite"
  steps:
    - name: Set Path Env
      shell: bash
      run: echo "GITHUB_ACTION_PATH=$GITHUB_ACTION_PATH" >> "$GITHUB_ENV"
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Set up python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      shell: bash
      run: |
        python -q -m pip install --upgrade pip
        pip install -q -r $GITHUB_ACTION_PATH/requirements.txt

    - name: Set dotenv file
      shell: bash
      run: echo OPENAI_API_KEY=${{ inputs.openai-key }} > $GITHUB_ACTION_PATH/.env

    - name: Test py file
      shell: bash
      run: python $GITHUB_ACTION_PATH/main.py
