name: Code to Manul Python
author: parkhs21

inputs:
  openai-key:
    required: true
outputs:
  result:
    value: ${{ steps.test-python.outputs.result }}

runs:
  using: "composite"
  steps:
    - name: Set Path Env
      shell: bash
      run: echo "GITHUB_ACTION_PATH=$GITHUB_ACTION_PATH" >> "$GITHUB_ENV"
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Set up python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      shell: bash
      run: pip install -q -r $GITHUB_ACTION_PATH/requirements.txt

    # - name: Set dotenv file
    #   shell: bash
    #   run: echo OPENAI_API_KEY=${{ inputs.openai-key }} > $GITHUB_ACTION_PATH/.env

    - name: Test py file
      shell: bash
      id: test-python
      run: python $GITHUB_ACTION_PATH/main.py
      env:
        OPENAI_API_KEY: ${{ inputs.openai-key }}

    - name: Upload file
      uses: actions/upload-artifact@v4
      id: upload-step
      with:
        name: answer-files
        path: answer.adoc

    - name: Current time
      shell: bash
      id: current-time
      run: echo "::set-output name=date::$(date -d '+9 hours' +'%b %d %R')"

    - name: Create issue
      uses: dacbd/create-issue-action@main
      with:
        token: ${{ github.token }}
        title: "[Manual] Manual Generated (${{ steps.current-time.outputs.date }})"
        labels: code-to-manual
        body: |
          ### Test

          아래 링크에서 로그를 확인하고, 첨부파일을 다운 받을 수 있습니다.

          첨부파일은 약 90일까지만 보관됩니다. 미리 다운 받아주세요.

          추가 수정이 필요할 경우, 커멘트를 달아 주세요.

          | Name     | Link   |
          |----------|--------|
          | Code     | ${{ github.server_url }}/${{ github.repository }}/tree/${{ github.sha }} |
          | Logs     | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |
          | Files    | ${{ steps.upload-artifacts.outputs.artifact-url }} |
